### ISSUE TITLE
Payload Currency Arrays Appear To 

### ISSUE THREAD

**Issue by smockensturm** [verbb/stamped-io#5]
**Description**
```
2021-08-12 16:02:25 [-][19346][-][error][stamped-io] Client error: `POST https://stamped.io/api/v2/201702/survey/reviews/bulk` resulted in a `400 Bad Request` response:
"data_array_needed"
```

**Steps to reproduce**
1. Order Something
2. Check the stamped error logs

**Additional info**
- Plugin version: 1.0.0
- Craft version: Pro 3.6.17
- Multi-site: No

**Additional context**
Commerce Version : 3.3.4.1

Here is a payload that once did work:

```
{
	<snipped>
	"orderCurrencyISO": "USD",
	<snipped>
}
```

Here is a payload that did not work

```
{
	<snipped>
	"orderCurrencyISO": {
		"id": "1",
		"iso": "USD",
		"primary": "1",
		"rate": "1.0000",
		"minorUnit": 2,
		"alphabeticCode": "USD",
		"currency": "US Dollar",
		"numericCode": 840,
		"entity": "VIRGIN ISLANDS (U.S.)"
	},
	<snipped>
}
```
Did something change? What changed?

**Comment by smockensturm** [comment]
Y'all gonna ever update your version / package with these currency patches?

**Comment by engram-design** [comment]
Totally didn't realise we never tagged a release for this. See [1.0.1](https://github.com/verbb/stamped-io/releases/tag/1.0.1)
